//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEBAPI_MVC_Crud
{
    using System;
    using System.Collections.Generic;
    
    public partial class Newempreg
    {
        public int Empid { get; set; }
        public string Empname { get; set; }
        public string Empemail { get; set; }
        public string Emplocation { get; set; }
        public string EmpDesignation { get; set; }
    }
}
